
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users_tags').del()
    .then(function () {
      // Inserts seed entries
      return knex('users_tags').insert([{
        "user_id": 8,
        "tag_id": 4
      }, {
        "user_id": 37,
        "tag_id": 13
      }, {
        "user_id": 31,
        "tag_id": 5
      }, {
        "user_id": 18,
        "tag_id": 10
      }, {
        "user_id": 33,
        "tag_id": 3
      }, {
        "user_id": 4,
        "tag_id": 2
      }, {
        "user_id": 7,
        "tag_id": 2
      }, {
        "user_id": 48,
        "tag_id": 1
      }, {
        "user_id": 46,
        "tag_id": 10
      }, {
        "user_id": 11,
        "tag_id": 10
      }, {
        "user_id": 3,
        "tag_id": 10
      }, {
        "user_id": 3,
        "tag_id": 6
      }, {
        "user_id": 12,
        "tag_id": 13
      }, {
        "user_id": 32,
        "tag_id": 9
      }, {
        "user_id": 41,
        "tag_id": 5
      }, {
        "user_id": 38,
        "tag_id": 11
      }, {
        "user_id": 18,
        "tag_id": 4
      }, {
        "user_id": 31,
        "tag_id": 16
      }, {
        "user_id": 22,
        "tag_id": 11
      }, {
        "user_id": 18,
        "tag_id": 15
      }, {
        "user_id": 41,
        "tag_id": 11
      }, {
        "user_id": 49,
        "tag_id": 12
      }, {
        "user_id": 6,
        "tag_id": 11
      }, {
        "user_id": 39,
        "tag_id": 4
      }, {
        "user_id": 14,
        "tag_id": 12
      }, {
        "user_id": 31,
        "tag_id": 15
      }, {
        "user_id": 36,
        "tag_id": 9
      }, {
        "user_id": 33,
        "tag_id": 14
      }, {
        "user_id": 31,
        "tag_id": 5
      }, {
        "user_id": 12,
        "tag_id": 16
      }, {
        "user_id": 12,
        "tag_id": 3
      }, {
        "user_id": 32,
        "tag_id": 14
      }, {
        "user_id": 40,
        "tag_id": 10
      }, {
        "user_id": 25,
        "tag_id": 5
      }, {
        "user_id": 19,
        "tag_id": 8
      }, {
        "user_id": 12,
        "tag_id": 7
      }, {
        "user_id": 12,
        "tag_id": 5
      }, {
        "user_id": 32,
        "tag_id": 12
      }, {
        "user_id": 50,
        "tag_id": 9
      }, {
        "user_id": 10,
        "tag_id": 15
      }, {
        "user_id": 24,
        "tag_id": 4
      }, {
        "user_id": 27,
        "tag_id": 13
      }, {
        "user_id": 26,
        "tag_id": 4
      }, {
        "user_id": 50,
        "tag_id": 12
      }, {
        "user_id": 28,
        "tag_id": 5
      }, {
        "user_id": 50,
        "tag_id": 9
      }, {
        "user_id": 8,
        "tag_id": 1
      }, {
        "user_id": 30,
        "tag_id": 11
      }, {
        "user_id": 14,
        "tag_id": 6
      }, {
        "user_id": 46,
        "tag_id": 4
      }]);
    });
};
