
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('items_tags').del()
    .then(function () {
      // Inserts seed entries
      return knex('items_tags').insert([{
        "id": 1,
        "item_id": 32,
        "tag_id": 16
      }, {
        "id": 2,
        "item_id": 21,
        "tag_id": 13
      }, {
        "id": 3,
        "item_id": 44,
        "tag_id": 9
      }, {
        "id": 4,
        "item_id": 32,
        "tag_id": 3
      }, {
        "id": 5,
        "item_id": 26,
        "tag_id": 8
      }, {
        "id": 6,
        "item_id": 21,
        "tag_id": 6
      }, {
        "id": 7,
        "item_id": 14,
        "tag_id": 8
      }, {
        "id": 8,
        "item_id": 5,
        "tag_id": 1
      }, {
        "id": 9,
        "item_id": 4,
        "tag_id": 2
      }, {
        "id": 10,
        "item_id": 1,
        "tag_id": 11
      }, {
        "id": 11,
        "item_id": 11,
        "tag_id": 12
      }, {
        "id": 12,
        "item_id": 47,
        "tag_id": 10
      }, {
        "id": 13,
        "item_id": 29,
        "tag_id": 11
      }, {
        "id": 14,
        "item_id": 13,
        "tag_id": 8
      }, {
        "id": 15,
        "item_id": 22,
        "tag_id": 9
      }, {
        "id": 16,
        "item_id": 8,
        "tag_id": 5
      }, {
        "id": 17,
        "item_id": 18,
        "tag_id": 1
      }, {
        "id": 18,
        "item_id": 11,
        "tag_id": 4
      }, {
        "id": 19,
        "item_id": 5,
        "tag_id": 16
      }, {
        "id": 20,
        "item_id": 35,
        "tag_id": 10
      }, {
        "id": 21,
        "item_id": 22,
        "tag_id": 7
      }, {
        "id": 22,
        "item_id": 39,
        "tag_id": 7
      }, {
        "id": 23,
        "item_id": 16,
        "tag_id": 13
      }, {
        "id": 24,
        "item_id": 21,
        "tag_id": 9
      }, {
        "id": 25,
        "item_id": 15,
        "tag_id": 3
      }, {
        "id": 26,
        "item_id": 20,
        "tag_id": 1
      }, {
        "id": 27,
        "item_id": 4,
        "tag_id": 12
      }, {
        "id": 28,
        "item_id": 32,
        "tag_id": 8
      }, {
        "id": 29,
        "item_id": 50,
        "tag_id": 11
      }, {
        "id": 30,
        "item_id": 44,
        "tag_id": 1
      }, {
        "id": 31,
        "item_id": 13,
        "tag_id": 11
      }, {
        "id": 32,
        "item_id": 46,
        "tag_id": 8
      }, {
        "id": 33,
        "item_id": 18,
        "tag_id": 16
      }, {
        "id": 34,
        "item_id": 14,
        "tag_id": 1
      }, {
        "id": 35,
        "item_id": 21,
        "tag_id": 4
      }, {
        "id": 36,
        "item_id": 49,
        "tag_id": 4
      }, {
        "id": 37,
        "item_id": 16,
        "tag_id": 1
      }, {
        "id": 38,
        "item_id": 38,
        "tag_id": 13
      }, {
        "id": 39,
        "item_id": 21,
        "tag_id": 1
      }, {
        "id": 40,
        "item_id": 48,
        "tag_id": 11
      }, {
        "id": 41,
        "item_id": 29,
        "tag_id": 5
      }, {
        "id": 42,
        "item_id": 20,
        "tag_id": 6
      }, {
        "id": 43,
        "item_id": 20,
        "tag_id": 16
      }, {
        "id": 44,
        "item_id": 37,
        "tag_id": 3
      }, {
        "id": 45,
        "item_id": 23,
        "tag_id": 10
      }, {
        "id": 46,
        "item_id": 49,
        "tag_id": 7
      }, {
        "id": 47,
        "item_id": 38,
        "tag_id": 11
      }, {
        "id": 48,
        "item_id": 24,
        "tag_id": 14
      }, {
        "id": 49,
        "item_id": 45,
        "tag_id": 1
      }, {
        "id": 50,
        "item_id": 25,
        "tag_id": 13
      }]);
    });
};
